---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-secret
  namespace: mariadb
spec:
  encryptedData:
    MARIADB_ROOT_PASSWORD: AgB1gDYSyXeAlwlROIxLPTcCfoMEOccJgKi/ziEnXbndqgyb/J89uhq1Yboux6MA3PXlQ16aYKtQH9556OkzTEd5dpJPXWXHoWG+zRBQgspy7L9XQpd9CtyApbOW5gNtK/Y+DFheenwNVAviPmbZmnctgQVwSQTvtBhYn2yLtjvVMgbHTGVr/i2wZ6vrXJS6iV6XrXSB6HybCNcxcXihFBFIfY8NPjrNugl+rRLAZH/fZDRl+50zSFgO+pxErllLH3Aqh1TYfnj2pvtlqvI5hpKUaMsswWWaW6pQInTPEiRChk8xlaIOQwZ0P3uS8cAEGxls/xndbLZ9chJU3JP/3qmkn8ZF6Vp/N6ZaRDiYQADBG+9/YBUysv6TJyDUhXlRXkF/2OWk8ZrUb3rPTUhOSm/aNENPRFYYnZeZVuMbsQrnvHlQztETkma/FyVmM+q2qdofLo52K7/aAW0eydEjCvyiuScNmIxa6wU92sGwvX1YWcQiJdEwY/Ja0t2g1X0aTnwcEisXmzyxrk8zj0mFHjt79BoF8KpBW8btJ6rvOFvrcl0D3EwNOF9/KIJRHw26lMoawGYlrA3WDNKMcfElohDDIBzXKbKw0PdKsz34FLNbebPd/FLI3LIvZkm2oqQwK/K51ZEoh2aqeB8jJlP5HFfozfUu8ODY+wijnKTMdMBZw0m5wqiN9zKTU4/cGZyYKvZ1po4h55cX8A==
  template:
    metadata:
      name: mariadb-secret
      namespace: mariadb
      labels:
        app: mariadb
    type: Opaque
